services:
  - type: web
    name: proshop-api
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: MONGO_URI
        value: mongodb+srv://sasinikhilmikkilineni:JEmaXajfuFiiOnVg@cluster0.rvactvu.mongodb.net/proshop
      - key: JWT_SECRET
        value: supersecret_change_me
      - key: PAYPAL_CLIENT_ID
        value: AfeI0t5-I4nrBCBl7-s6jD6vC8vRW0b7-dKsO0LG5NwHv5kFJCKeDqmGxT7iJPJF0Ff2gVf04UM0q3Tg
